#cloud-config
write_files:
  - path: /etc/rc.local
    permissions: "0755"
    owner: root
    content: |
      #!/bin/bash
      mkdir -p /var/log/boot
      exec > /var/log/boot/cloud-config.log 2>&1
      export INSTANCE_ID=$(wget -qO- http://169.254.169.254/latest/meta-data/instance-id)
      wait-for-docker
      echo 'docker run --rm radial/busyboxplus:curl curl $@' > /usr/bin/curl && chmod +x /usr/bin/curl
      docker run -d --name rancher \
        -v /var/lib/rancher:/var/lib/rancher \
        -p 80:80 -p 443:443 \
        rancher/rancher:${rancher_version} \
        --acme-domain ${name}.${domain}
rancher:
  docker:
    engine: ${docker_version}
    log_driver: "json-file"
    log_opts:
      max-file: "3"
      max-size: "100m"
      labels: "production"
  services_include:
    kernel-headers: true
